### ISSUE TITLE
API for gene, reaction, and metabolite tooltips and information boxes

### ISSUE THREAD

**Issue by andreasprlic** [zakandrewking/escher#112]
Hi,

Escher looks amazing. Would it be possible to show the "descriptive name" of a reaction, when moving the mouse over a reaction names? E.g. PDH could have a tooltip of "pyruvate dehydrogenase ". That would make following some of the pathways much easier.

Thanks,

Andreas

**Comment by zakandrewking** [comment]
Definitely. We can add a tooltip without much trouble.

I would also like to create a more general interface for retrieving content in a popup window when users mouseover or click an Escher object—something with an API so it could be extended. Content could include:

- descriptive names
- chemical formulae
- links to the BiGG database
- metabolite structures from chemspider
- instead of showing a popup, use the click to perform arbitrary javascript (e.g. link to another page)

**Comment by andreasprlic** [comment]
Great idea re. API. That would allow us to add additional links to searches in our database, ligand summary pages, etc.

Just for completeness: would be great to have tooltips also for metabolites. E.g. most people probably understand Acetyl CoA better than accoa_c .
