### ISSUE TITLE
Change direction of reaction 

### ISSUE THREAD

**Issue by jotech** [zakandrewking/escher#140]
The direction of a reaction is somehow arbitrarily defined in the model.
(`A <-> B` vs `B <-> A`)
When loading csv data sometimes model directions do not fit with the data.
Would be nice to have an option to change the default direction in escher (instead of changing the model).

**Comment by zakandrewking** [comment]
Yeah I can see the sense behind that. The direction in the model exists as
an implementation detail (you need to be able to specify a positive
direction and a negative direction).

Can you be more specific about a case where switching the direction makes
sense? this will help me think about solutions.

**Comment by jotech** [comment]
For sure ;) Issue occurred while loading reaction data into central metabolism map using iJO1366 model.
Consider the TCA, the default direction of SUCOAS is succ-->succcoa, which is the reductive case.
But former reactions like CS, ACONTa/b, ICDHyr and AKGDH are defined according to oxidative case.
That's why loaded data can lead to different arrow colors which is correct but attracts the eye to something which is caused only arbitrarily.
Same happens in glucolysis. Would be best to define models more consistently but this is not always possible.  Desired direction also depends on the pathway you want to depict and is therefore ambiguous.

**Comment by zakandrewking** [comment]
My approach to this issue has been to turn on Absolute Value for reaction
coloring (the 'Abs' checkbox in Settings). Have you tried that? Does that
help at all with your case?

**Comment by bdelepine** [comment]
Hi @zakandrewking,

I had some trouble interpreting a flux map and, long story short, it turned out that some reactions from my model where not in the same direction as their counterpart from BiGG which mess some arrow directionality up. I can open another ticket if you prefer.

I thought arrow directionality would be updated to match the data file (negative value displayed in reverse) AND the model file provided (as a reference for what is the "positive" direction, which I assumed to be left-to-right).
In the end I believe that the base/default direction of the reaction arrows is always the one from the map file and not the one from the model, that is totally ignored. 

Am I right? I can provide tests if you wish so.

The behavior I would like would be either:
* a silent update of all directions arrows on model load
* the possibility to update the directionality of all reactions from the map based on the ones from the model, just like names and reaction rules
* some magical way to explicitly draw the reaction in the direction of the model :smile:

**Comment by zakandrewking** [comment]
@jotech if you're still watching this, the latest beta release of Escher is up now:

https://escher.github.io

Option 2 above is implemented!

> the possibility to update the directionality of all reactions from the map based on the ones from the model, just like names and reaction rules

let me know if it's working for you
