### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by joaocardoso** [zakandrewking/escher#161]
Hi Zak,

We are running into some trouble to run load escher maps:

https://www.dropbox.com/s/k9mi5xz2bagcsz4/Screenshot%202016-05-17%2013.19.46.png?dl=0

The npmcdn server is returning a 403 error.

Best,

Joao

**Comment by zakandrewking** [comment]
Looks like the issue is with the `?v=#` at the end of the URL. Any idea how that was added?

Zak



On Tue, May 17, 2016 at 4:24 AM -0700, "João Gonçalo Rocha Cardoso" <notifications@github.com> wrote:












Hi Zak,



We are running into some trouble to run load escher maps:



https://www.dropbox.com/s/k9mi5xz2bagcsz4/Screenshot%202016-05-17%2013.19.46.png?dl=0



The npmcdn server is returning a 403 error.



Best,



Joao

**Comment by joaocardoso** [comment]
Nope. Can it be the browser or Jupiter. I do confirm that it works without the "?v=#" if I go to the browser.

**Comment by zakandrewking** [comment]
Check out 1.4.4
