### ISSUE TITLE
Save PNG still broken in Safari 10.1

### ISSUE THREAD

**Issue by zakandrewking** [zakandrewking/escher#179]
Safari 10.1 fixes download for JSON and SVG, but the PNG download still isn't working

**Comment by matyasfodor** [comment]
@zakandrewking what's the exact issue here? I tried PNG download with master HEAD, and it seems working fine on Safari (I'm using Safari version 11.0.3 (13604.5.6)) but I guess you can expect your users to use the latest one. I made this png:
![saved_map-3](https://user-images.githubusercontent.com/14725644/35938709-464fa016-0c4a-11e8-9625-24aad6da59eb.png)
The only think I noticed is that it zooms in to the top left corner, and the next moment the image is downloaded, then it zooms back. Also I wasn't able to save the current viewport, but I guess that's intentional.

**Comment by zakandrewking** [comment]
Thanks for looking at this. I think it was broken in Safari <= 10.x, but 11 has more modern web APIs. Closing!
