### ISSUE TITLE
Load KGML file in Escher

### ISSUE THREAD

**Issue by anusurendra** [zakandrewking/escher#202]
Hi,

I am wondering if there is a way to load a KEGG KGML file into Escher as a map?

Thanks

**Comment by zakandrewking** [comment]
I see that you got ahold of Andreas by email. @draeger if it's OK with you, I'd like to paste your response in this issue, in case someone else has the same question.

**Comment by anusurendra** [comment]
Zak, 
Yes you can. However, I am having an issue when I use the EscherConverter to convert my sbgn to escher format. It seems to be stuck at _"lambda$convert$29 --- INFO: glyph with id 'glyph170' has class 'process', converting to reaction + mid-marker". I have attached the log file. I understand the Andreas is busy with Grants. But I figured if you get a chance to take a look at the issue later on then the log file would be good.





[escherconverter.log](https://github.com/zakandrewking/escher/files/1360019/escherconverter.log)
[eco00860_test.sbgn.tar.gz](https://github.com/zakandrewking/escher/files/1360007/eco00860_test.sbgn.tar.gz)

**Comment by draeger** [comment]
Yes, there is an automatic way to do this. In fact, you have even choices between two ways (of which I am aware).

The software KEGGtranslator (see https://github.com/cogsys-tuebingen/KEGGtranslator and documentation at http://www.cogsys.cs.uni-tuebingen.de/software/KEGGtranslator/doc/) is able to automatically pull information from KEGG database and to augment the information. We spent three years developing it and coordinated its output with the KEGG team.

Now, KEGGtranslator can create SBML files that include layout information. Depending on settings of the program this can look more or less like the original image from KEGG. There is one key publication about the algorithm in this software that is recommended to read because it gives you information about a lot of pitfalls that people frequently encounter when dealing with KEGG (see https://bmcsystbiol.biomedcentral.com/articles/10.1186/1752-0509-7-15). As you will understand when reading this article, the images that KEGG provides are not always what really happens. Details are often omitted. For instance, there might be reactions from Glucose to Glucose-1-phosphate without indicating that ATP is involved. KEGG does it like this to make the map easier to comprehend (as they think, I actually don't agree). There are other problems, see the article.

KEGGtranslator will insert all missing reaction participants. The problem with this is that there are no graphical coordinates for these additional components. Hence, the result won't really look very pretty. But it will have much more information than the original KEGG map.

So, save the result as SBML on your computer. KEGGtranslator also allows you to export to SBGN-ML.

As an alternative, you may want to consider the tool described in this article: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-14-250

It has been designed to make maps that look similar to KEGG but will be encoded in SBGN-ML, another community standard format. With this tool, you may obtain nicer looking graphs but with less information content compared to the output of KEGGtranslator.

Now, your SBGN-ML or SBML file needs to be converted to Escher's JSON. Do that with EscherConverter (see https://github.com/SBRG/EscherConverter). Just use drag and drop to pull the file into EscherConverter and save to JSON. The result can be loaded into Escher.

As said, don't expect it to look exactly like KEGG's image. This will hardly be possible because of the many difficulties with the information representation in that database and the different conversion steps.

I hope this helps!
